{
    "swagger": "2.0",
    "info": {
        "title": "hmi-apim-api",
        "version": "1.0"
    },
    "host": "hmi-apim-sbox.sandbox.platform.hmcts.net",
    "basePath": "/hmi",
    "schemes": ["http"],
    "securityDefinitions": {
        "apiKeyHeader": {
            "type": "apiKey",
            "name": "Ocp-Apim-Subscription-Key",
            "in": "header"
        },
        "apiKeyQuery": {
            "type": "apiKey",
            "name": "subscription-key",
            "in": "query"
        }
    },
    "security": [{
        "apiKeyHeader": []
    }, {
        "apiKeyQuery": []
    }],
    "paths": {
        "/hearings": {
            "post": {
                "description": "Request Hearing",
                "operationId": "request-hearing",
                "summary": "Request Hearing",
                "parameters": [{
                    "name": "Source-System",
                    "in": "header",
                    "description": "soruce of the request initiation\n",
                    "required": true,
                    "type": "string",
                    "enum": ["CFT"]
                }, {
                    "name": "Destination-System",
                    "in": "header",
                    "description": "Target/Backend system that is supposed to consume the request message.",
                    "required": true,
                    "type": "string",
                    "enum": ["S&L"]
                }, {
                    "name": "Request-Created-At",
                    "in": "header",
                    "description": "Date and time of request initiation.",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Request-Type",
                    "in": "header",
                    "description": "Type of request",
                    "required": true,
                    "type": "string",
                    "enum": ["THEFT", "ASSAULT"]
                }, {
                    "name": "Request-Processed-At",
                    "in": "header",
                    "description": "Date & Time of Request Processing",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Accept",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "Content-Type",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "rh-def",
                    "in": "body",
                    "schema": {
                        "$ref": "#/definitions/rh-def"
                    }
                }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "",
                        "examples": {
                            "application/json": {
                                "response code ": 200,
                                "description": "The request was received successfully."
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Hearing",
                "operationId": "delete-hearing",
                "summary": "Delete Hearing",
                "parameters": [{
                    "name": "Source-System",
                    "in": "header",
                    "type": "string",
                    "enum": ["CFT"]
                }, {
                    "name": "Destination-System",
                    "in": "header",
                    "type": "string",
                    "enum": ["S&L"]
                }, {
                    "name": "Request-Created-At",
                    "in": "header",
                    "type": "string",
                    "enum": ["2018-01-29 20:36:01Z"]
                }, {
                    "name": "Request-Type",
                    "in": "header",
                    "type": "string",
                    "enum": ["THEFT"]
                }, {
                    "name": "Content-Type",
                    "in": "header",
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "Accept",
                    "in": "header",
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "Request-Processed-At",
                    "in": "header",
                    "type": "string",
                    "enum": ["2018-01-29 20:36:01Z"]
                }, {
                    "name": "rh-del-def",
                    "in": "body",
                    "schema": {
                        "$ref": "#/definitions/rh-del-def"
                    }
                }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "",
                        "examples": {
                            "application/json": {
                                "statusCode": 200,
                                "message": "Hearing successfully deleted"
                            }
                        }
                    }
                }
            }
        },
        "/hearings/{hearing-id}": {
            "put": {
                "description": "Update Hearing",
                "operationId": "update-hearing",
                "summary": "Update Hearing",
                "parameters": [{
                    "name": "hearing-id",
                    "in": "path",
                    "required": true,
                    "type": "string",
                    "enum": ["CASE123432"]
                }, {
                    "name": "Source-System",
                    "in": "header",
                    "description": "soruce of the request initiation\n",
                    "required": true,
                    "type": "string",
                    "enum": ["CFT"]
                }, {
                    "name": "Destination-System",
                    "in": "header",
                    "description": "Target/Backend system that is supposed to consume the request message.",
                    "required": true,
                    "type": "string",
                    "enum": ["S&L"]
                }, {
                    "name": "Request-Created-At",
                    "in": "header",
                    "description": "Date and time of request initiation.",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Request-Type",
                    "in": "header",
                    "description": "Type of request",
                    "required": true,
                    "type": "string",
                    "enum": ["THEFT", "ASSAULT"]
                }, {
                    "name": "Request-Processed-At",
                    "in": "header",
                    "description": "Date and time of request processing",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Accept",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "Content-Type",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "rh-upd-def",
                    "in": "body",
                    "schema": {
                        "$ref": "#/definitions/rh-upd-def"
                    },
                    "description": "[ \n  { \n    \"apiVersion\": \"V1.00103\", \n    \"transactionIdHmcts\": \"5f2bffce09fb0feadaf7b906\", \n    \"timeStamp\": \"12:15:22\", \n    \"source\": \"T\", \n    \"Destination\": \"SL\", \n    \"apiKey\": \"372ab28b-5830-45a6-916f-d73b03366af5\", \n    \"apiAuthToken\": \"kjlhsdg74iah2894648>IUH8hs@39Hi\", \n    \"corrolationID\": \"5f2bffce7bfb7bd35546964e\", \n    \"caseObject\": { \n      \"caseIdHmcts\": 1.2904144820148569e+23, \n      \"caseTitle\": \"Marcie Ross \\\"vs\\\" Phyllis Guzman\", \n      \"caseJurisdiction\": \"this.source\", \n      \"caseService\": \"MatterCat2\", \n      \"CaseType\": \"MatterCode2\", \n      \"caseSubType\": \"MatterType1\", \n      \"caseCourt\": \"Spennymoor,County Durham,England\", \n      \"caseRegistered\": \"2015-08-20T02:06:45 -01:00\", \n      \"caseComments\": \"Mollit excepteur elit duis adipisicing mollit. Adipisicing veniam deserunt commodo pariatur aute do. Et nulla excepteur quis anim sit. Cillum aliqua et id adipisicing ut ea veniam Lorem dolore sunt culpa duis. Tempor dolor veniam laborum deserunt ullamco id officia elit nisi. Et reprehenderit est eu reprehenderit consequat non excepteur aliquip aute ullamco voluptate. Commodo ex id irure culpa ut mollit Lorem.\\r\\nPariatur consectetur quis commodo labore consectetur ullamco irure qui et consectetur deserunt ad. Magna cillum ipsum aliqua velit reprehenderit excepteur. Tempor incididunt voluptate et dolor. Aute et adipisicing cillum dolor sint duis proident reprehenderit minim est adipisicing quis reprehenderit occaecat. Veniam ut Lorem ex id ea reprehenderit.\\r\\nMagna minim elit eiusmod duis voluptate. Commodo qui nulla sunt aute cillum sint officia. Anim exercitation incididunt nisi eiusmod laborum ullamco exercitation esse elit est reprehenderit aliquip nulla minim.\\r\\n\", \n      \"caseSource\": \"\", \n      \"caseKind\": \"Kind_3\", \n      \"caseRelatedCaseIdHmcts\": \"\", \n      \"UpdateObject\": \"Update is to send hearing outcome\" \n    }, \n    \"listing\": { \n      \"listingId\": \"5f2bffceaab99eababcf7f0d\", \n      \"listingStartDate\": \"2018-02-19T02:41:04 -00:00\", \n      \"listingEndDate\": \"2014-11-26T12:03:38 -00:00\", \n      \"listingDuration\": 120, \n      \"listingType\": \"new\", \n      \"listingPriority\": \"High\", \n      \"listingNumberAttendees\": 5, \n      \"listingPartiesMethod\": \"Video Conf\" \n    } \n  }, \n  { \n    \"apiVersion\": \"V1.00103\", \n    \"transactionIdHmcts\": \"5f2bffce6962d03e8b73e76f\", \n    \"timeStamp\": \"12:15:22\", \n    \"source\": \"CR\", \n    \"Destination\": \"SL\", \n    \"apiKey\": \"c712b357-aaa2-4129-8394-68faa217e02d\", \n    \"apiAuthToken\": \"kjlhsdg74iah2894648>IUH8hs@39Hi\", \n    \"corrolationID\": \"5f2bffceb3f102a67269f969\", \n    \"caseObject\": { \n      \"caseIdHmcts\": 1.9830463505746397e+24, \n      \"caseTitle\": \"Lori Clements \\\"vs\\\" Dawson Suarez\", \n      \"caseJurisdiction\": \"this.source\", \n      \"caseService\": \"MatterCat3\", \n      \"CaseType\": \"MatterCode1\", \n      \"caseSubType\": \"MatterType1\", \n      \"caseCourt\": \"Peterborough,Cambridgeshire,England\", \n      \"caseRegistered\": \"2014-06-23T02:49:41 -01:00\", \n      \"caseComments\": \"Amet irure ea consequat non exercitation est est qui commodo. Laborum officia ullamco exercitation laborum id dolor reprehenderit ullamco. Ut qui deserunt duis aliqua et reprehenderit magna laborum ullamco cillum.\\r\\nAnim ipsum exercitation cillum quis exercitation aliqua culpa dolor nostrud. Fugiat ut laboris dolore laborum excepteur. Do eu qui proident cillum.\\r\\nCillum est ullamco veniam nulla aliqua enim. Aliqua velit ipsum nulla anim reprehenderit. Sit est ex incididunt exercitation. Et et esse laborum incididunt non.\\r\\n\", \n      \"caseSource\": \"\", \n      \"caseKind\": \"Kind_1\", \n      \"caseRelatedCaseIdHmcts\": \"\", \n      \"UpdateObject\": \"Update is to close hearing as ressolved\" \n    }, \n    \"listing\": { \n      \"listingId\": \"5f2bffcec0d5d73e929923fa\", \n      \"listingStartDate\": \"2015-01-02T05:29:13 -00:00\", \n      \"listingEndDate\": \"2014-09-08T03:13:14 -01:00\", \n      \"listingDuration\": 30, \n      \"listingType\": \"new\", \n      \"listingPriority\": \"High\", \n      \"listingNumberAttendees\": 6, \n      \"listingPartiesMethod\": \"In Person\" \n    } \n  }, \n  { \n    \"apiVersion\": \"V1.00103\", \n    \"transactionIdHmcts\": \"5f2bffcea47aedacc86d35cf\", \n    \"timeStamp\": \"12:15:22\", \n    \"source\": \"CR\", \n    \"Destination\": \"SL\", \n    \"apiKey\": \"c5ff9983-9bce-4f06-aaaf-a2c531647ab7\", \n    \"apiAuthToken\": \"kjlhsdg74iah2894648>IUH8hs@39Hi\", \n    \"corrolationID\": \"5f2bffce2b8e44284e810e02\", \n    \"caseObject\": { \n      \"caseIdHmcts\": 1.8047818623646046e+24, \n      \"caseTitle\": \"Noemi Cruz \\\"vs\\\" Tammi Wade\", \n      \"caseJurisdiction\": \"this.source\", \n      \"caseService\": \"MatterCat1\", \n      \"CaseType\": \"MatterCode1\", \n      \"caseSubType\": \"MatterType2\", \n      \"caseCourt\": \"Par,Cornwall,England\", \n      \"caseRegistered\": \"2020-01-28T10:58:01 -00:00\", \n      \"caseComments\": \"Tempor officia aliqua exercitation id. Ipsum quis ipsum eiusmod aute velit aute cillum deserunt ea. Voluptate reprehenderit ex incididunt dolor irure laboris occaecat esse tempor est do. Ea labore velit irure occaecat elit ullamco nostrud elit amet. Irure proident dolore mollit sint nulla tempor irure deserunt aute mollit adipisicing nostrud sint aute. Non laboris aute ad qui. Magna aliquip duis pariatur ea dolore nostrud veniam consectetur deserunt anim nulla laboris.\\r\\nAliqua adipisicing sit proident culpa tempor minim cillum in Lorem labore nostrud. Duis aliquip esse ipsum Lorem culpa commodo culpa commodo cillum aute. Aute commodo nisi nisi voluptate culpa adipisicing aliquip tempor cupidatat ut. Fugiat sunt ex elit exercitation eiusmod Lorem incididunt nostrud occaecat culpa aute duis duis cupidatat. Reprehenderit dolor dolor ea id enim sit consequat nisi non deserunt do. Reprehenderit nulla non magna aute quis ea in ut. Sint velit occaecat Lorem voluptate labore do aliqua dolor Lorem laborum nostrud laboris mollit.\\r\\nConsequat Lorem voluptate quis proident sunt laboris voluptate commodo minim proident deserunt laborum eu occaecat. Commodo deserunt et do laboris dolore occaecat voluptate occaecat consectetur qui. Occaecat laborum ad consectetur nisi quis tempor deserunt.\\r\\n\", \n      \"caseSource\": \"\", \n      \"caseKind\": \"Kind_2\", \n      \"caseRelatedCaseIdHmcts\": \"\", \n      \"UpdateObject\": \"Update is to cancel hearing\" \n    }, \n    \"listing\": { \n      \"listingId\": \"5f2bffce815213e39b34d92e\", \n      \"listingStartDate\": \"2017-02-22T01:25:38 -00:00\", \n      \"listingEndDate\": \"2017-05-04T04:09:55 -01:00\", \n      \"listingDuration\": 60, \n      \"listingType\": \"Update\", \n      \"listingPriority\": \"Standard\", \n      \"listingNumberAttendees\": 5, \n      \"listingPartiesMethod\": \"In Person\" \n    } \n  }, \n  { \n    \"apiVersion\": \"V1.00103\", \n    \"transactionIdHmcts\": \"5f2bffce29c77b6fef1e7488\", \n    \"timeStamp\": \"12:15:22\", \n    \"source\": \"CR\", \n    \"Destination\": \"SL\", \n    \"apiKey\": \"c8a10a89-10cb-4c9b-8a35-035722e06378\", \n    \"apiAuthToken\": \"kjlhsdg74iah2894648>IUH8hs@39Hi\", \n    \"corrolationID\": \"5f2bffcece5eff130dc3731e\", \n    \"caseObject\": { \n      \"caseIdHmcts\": 1.9359662341963678e+24, \n      \"caseTitle\": \"Ofelia Farrell \\\"vs\\\" Estrada Bradshaw\", \n      \"caseJurisdiction\": \"this.source\", \n      \"caseService\": \"MatterCat2\", \n      \"CaseType\": \"MatterCode3\", \n      \"caseSubType\": \"MatterType3\", \n      \"caseCourt\": \"Flitwick,Bedfordshire,England\", \n      \"caseRegistered\": \"2016-08-27T11:36:03 -01:00\", \n      \"caseComments\": \"Culpa irure incididunt eu eiusmod. Sunt nostrud veniam ullamco duis est. Veniam cillum laboris qui Lorem sit.\\r\\nAmet tempor nulla aliqua velit occaecat in aute ad pariatur. Velit sit fugiat ipsum nostrud non in proident consequat do tempor. Esse mollit amet aliqua irure labore deserunt qui occaecat. Ipsum sunt magna incididunt id esse officia quis incididunt tempor enim adipisicing aute do. Cupidatat nulla ea consectetur eu. Est non velit enim qui officia consequat labore ex culpa laborum amet ex velit ipsum. Eiusmod pariatur officia qui elit incididunt sunt ut laborum culpa aliquip aute occaecat et.\\r\\nTempor voluptate nostrud mollit deserunt anim mollit sunt tempor quis ea reprehenderit labore. Voluptate consequat fugiat velit magna aute consequat commodo. Nulla magna consequat cillum Lorem quis elit Lorem mollit nisi fugiat sint. In ullamco mollit pariatur deserunt quis pariatur ex. Aliquip amet cillum est sit nisi.\\r\\n\", \n      \"caseSource\": \"\", \n      \"caseKind\": \"Kind_4\", \n      \"caseRelatedCaseIdHmcts\": \"\", \n      \"UpdateObject\": \"Update is to cancel hearing\" \n    }, \n    \"listing\": { \n      \"listingId\": \"5f2bffce618d24fbeef1df41\", \n      \"listingStartDate\": \"2014-09-21T06:15:23 -01:00\", \n      \"listingEndDate\": \"2019-02-13T09:54:25 -00:00\", \n      \"listingDuration\": 120, \n      \"listingType\": \"Update\", \n      \"listingPriority\": \"Low\", \n      \"listingNumberAttendees\": 4, \n      \"listingPartiesMethod\": \"Video Conf\" \n    } \n  }, \n  { \n    \"apiVersion\": \"V1.00103\", \n    \"transactionIdHmcts\": \"5f2bffcef2495fdf2350014f\", \n    \"timeStamp\": \"12:15:22\", \n    \"source\": \"CR\", \n    \"Destination\": \"SL\", \n    \"apiKey\": \"48949ba2-caeb-4284-ba6a-7ff794c1a93f\", \n    \"apiAuthToken\": \"kjlhsdg74iah2894648>IUH8hs@39Hi\", \n    \"corrolationID\": \"5f2bffce17c98d58c5203f7f\", \n    \"caseObject\": { \n      \"caseIdHmcts\": 2.914487009352408e+24, \n      \"caseTitle\": \"Jasmine Giles \\\"vs\\\" Powell Townsend\", \n      \"caseJurisdiction\": \"this.source\", \n      \"caseService\": \"MatterCat2\", \n      \"CaseType\": \"MatterCode2\", \n      \"caseSubType\": \"MatterType2\", \n      \"caseCourt\": \"St Blazey,Cornwall,England\", \n      \"caseRegistered\": \"2014-01-19T08:33:02 -00:00\", \n      \"caseComments\": \"Do aliquip labore ea elit dolor consequat ut laborum sit est ad. Culpa sit velit aute nisi. Proident aliquip ea incididunt cupidatat nostrud aliqua in esse tempor qui sit. Cupidatat qui proident proident et et ut.\\r\\nEiusmod excepteur reprehenderit tempor veniam mollit nostrud. Lorem exercitation laborum elit nisi dolore eiusmod tempor nisi. Sit laboris deserunt cupidatat consectetur non. Anim commodo laborum aliquip qui nulla enim esse. Quis sint sint irure deserunt tempor exercitation excepteur anim. Culpa commodo ex amet minim ad occaecat consectetur id.\\r\\nDeserunt commodo amet culpa elit minim pariatur adipisicing magna. Aliqua aliquip cillum commodo proident est aute consectetur aliqua ipsum velit deserunt consequat. Lorem est enim ut magna amet consectetur minim laborum ex ea. Occaecat Lorem ut anim ipsum laborum et eiusmod ullamco. Do officia ea anim incididunt esse elit anim nulla anim dolor commodo. Sint consectetur mollit irure ex et ullamco duis proident.\\r\\n\", \n      \"caseSource\": \"\", \n      \"caseKind\": \"Kind_4\", \n      \"caseRelatedCaseIdHmcts\": \"\", \n      \"UpdateObject\": \"Update is to cancel hearing\" \n    }, \n    \"listing\": { \n      \"listingId\": \"5f2bffceef36b0eaf339d884\", \n      \"listingStartDate\": \"2014-12-17T07:57:08 -00:00\", \n      \"listingEndDate\": \"2014-12-17T11:10:57 -00:00\", \n      \"listingDuration\": 120, \n      \"listingType\": \"Update\", \n      \"listingPriority\": \"Standard\", \n      \"listingNumberAttendees\": 4, \n      \"listingPartiesMethod\": \"Tele Conf\" \n    } \n  }, \n  { \n    \"apiVersion\": \"V1.00103\", \n    \"transactionIdHmcts\": \"5f2bffce39c59aa37c0ddeb7\", \n    \"timeStamp\": \"12:15:22\", \n    \"source\": \"F\", \n    \"Destination\": \"SL\", \n    \"apiKey\": \"97551667-e9ea-4c13-83d8-f79ed5fb3186\", \n    \"apiAuthToken\": \"kjlhsdg74iah2894648>IUH8hs@39Hi\", \n    \"corrolationID\": \"5f2bffce90a69eb81aaec725\", \n    \"caseObject\": { \n      \"caseIdHmcts\": 7.051483066471055e+23, \n      \"caseTitle\": \"Chang Ward \\\"vs\\\" Justine Johns\", \n      \"caseJurisdiction\": \"this.source\", \n      \"caseService\": \"MatterCat2\", \n      \"CaseType\": \"MatterCode2\", \n      \"caseSubType\": \"MatterType3\", \n      \"caseCourt\": \"Darlington,County Durham,England\", \n      \"caseRegistered\": \"2019-11-14T04:28:11 -00:00\", \n      \"caseComments\": \"Occaecat consectetur eiusmod laboris ullamco aute ea incididunt veniam duis cillum. Ullamco qui duis reprehenderit laborum cillum incididunt nulla aute in pariatur fugiat commodo duis dolore. Aute officia quis nulla laboris laboris occaecat.\\r\\nIncididunt pariatur id ad id sint nisi proident duis elit. Consequat deserunt id mollit duis do qui dolor sit pariatur eiusmod. Laboris laborum aute excepteur dolor occaecat. Culpa labore laborum aliqua nulla cupidatat do.\\r\\nMinim ullamco reprehenderit quis sit laboris irure velit veniam pariatur qui dolore pariatur fugiat. Sint proident incididunt ea excepteur aliquip consectetur exercitation esse ea consequat voluptate proident. Adipisicing enim amet incididunt ipsum laboris consectetur sunt.\\r\\n\", \n      \"caseSource\": \"\", \n      \"caseKind\": \"Kind_2\", \n      \"caseRelatedCaseIdHmcts\": \"\", \n      \"UpdateObject\": \"Update is to send hearing outcome\" \n    }, \n    \"listing\": { \n      \"listingId\": \"5f2bffcee0b6aa870e82f007\", \n      \"listingStartDate\": \"2017-11-04T07:39:20 -00:00\", \n      \"listingEndDate\": \"2015-12-30T09:16:45 -00:00\", \n      \"listingDuration\": 90, \n      \"listingType\": \"Second\", \n      \"listingPriority\": \"Standard\", \n      \"listingNumberAttendees\": 5, \n      \"listingPartiesMethod\": \"Video Conf\" \n    } \n  } \n] \n"
                }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {
                    "201": {
                        "description": "Successfully updated hearing",
                        "examples": {
                            "application/json": {
                                "response code": 201,
                                "description": "The request was received successfully."
                            }
                        }
                    }
                }
            }
        },
        "/": {
            "get": {
                "description": "Health-Check",
                "operationId": "health-check",
                "summary": "Health-Check",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/resources": {
            "get": {
                "description": "Retrieve list of resources",
                "operationId": "resources",
                "summary": "Resources",
                "parameters": [{
                    "name": "Source-System",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["CFT"]
                }, {
                    "name": "Destination-System",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["S&L"]
                }, {
                    "name": "Request-Created-At",
                    "in": "header",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Request-Type",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["THEFT", "ASSAULT"]
                }, {
                    "name": "Request-Processed-At",
                    "in": "header",
                    "description": "Date & Time of Request processing",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Accept",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "Content-Type",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }],
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/rh-res-resources"
                        },
                        "examples": {
                            "application/json": "[\n\t{\n\t\t\"VenueID\": \"V123\",\n\t\t\"JurisdictionID\": \"J123\",\n\t\t\"FacilityID\": \"F123\",\n\t\t\"LocationID\": \"L123\",\n\t\t\"RegionID\": \"R123\",\n\t\t\"AddressID\": \"A123\",\n\t\t\"UPRN\": \"djksfxzcdas\",\n\t\t\"ePIMs\": \"djfsdads\",\n\t\t\"VenueName\": \"VName\",\n\t\t\"VenueType\": \"Vtype\",\n\t\t\"FacilityServiceLead\": \"asdjkfahjd\",\n\t\t\"ReportingSIteName\": \"asfdhahjks\",\n\t\t\"CourtType\": \"Civil\",\n\t\t\"JoinedBuildingYN\": \"Y\",\n\t\t\"OtherAgenciesAtSite\": \"N\",\n\t\t\"FlexibleOpsHours\":\"Y\",\n\t\t\"Cluster\": \"CCC123\",\n\t\t\"JudicialLead\": \"asdkjfhd\",\n\t\t\"DCJLCJLJArea\": \"dsfhj\",\n\t\t\"Status\": \"Open\",\n\t\t\"OpeningTimes\": \"0800 - 1600\",\n\t\t\"OpenToPublic\": \"N\"\n\t}\n]"
                        }
                    }
                }
            }
        },
        "/resources/{resourceId}": {
            "get": {
                "description": "Retrieve resource by id",
                "operationId": "resource-by-id",
                "summary": "Resorce By ID",
                "parameters": [{
                    "name": "resourceId",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Source-System",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["CFT"]
                }, {
                    "name": "Destination-System",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["S&L"]
                }, {
                    "name": "Request-Created-At",
                    "in": "header",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Request-Type",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["THEFT", "ASSAULT"]
                }, {
                    "name": "Request-Processed-At",
                    "in": "header",
                    "description": "Date & Time of Request Processing",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Accept",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "Content-Type",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }],
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/rh-res-resource"
                        },
                        "examples": {
                            "application/json": {
                                "VenueID": "V123",
                                "JurisdictionID": "J123",
                                "FacilityID": "F123",
                                "LocationID": "L123",
                                "RegionID": "R123",
                                "AddressID": "A123",
                                "UPRN": "djksfxzcdas",
                                "ePIMs": "djfsdads",
                                "VenueName": "VName",
                                "VenueType": "Vtype",
                                "FacilityServiceLead": "asdjkfahjd",
                                "ReportingSIteName": "asfdhahjks",
                                "CourtType": "Civil",
                                "JoinedBuildingYN": "Y",
                                "OtherAgenciesAtSite": "N",
                                "FlexibleOpsHours": "Y",
                                "Cluster": "CCC123",
                                "JudicialLead": "asdkjfhd",
                                "DCJLCJLJArea": "dsfhj",
                                "Status": "Open",
                                "OpeningTimes": "0800 - 1600",
                                "OpenToPublic": "N"
                            }
                        }
                    }
                }
            }
        },
        "/schedules": {
            "get": {
                "description": "Schedules",
                "operationId": "schedule",
                "summary": "Schedule",
                "parameters": [{
                    "name": "hearing_date ",
                    "in": "query",
                    "type": "string",
                    "enum": ["2020-12-31T07:57:08 -00:00"]
                }, {
                    "name": "hearing_venue_id",
                    "in": "query",
                    "type": "string",
                    "enum": ["5f2bffce29c77b6fef1e7488"]
                }, {
                    "name": "hearing_room_id",
                    "in": "query",
                    "type": "string",
                    "enum": ["5f2bffce29c77b6fef1e7499"]
                }, {
                    "name": "hearing_session_id_casehq",
                    "in": "query",
                    "type": "string",
                    "enum": ["5f2bffce29c77b6fef1e7400"]
                }, {
                    "name": "hearing_case_id_hmcts",
                    "in": "query",
                    "type": "string",
                    "enum": ["5f2bffce29c77b6fef1e7411"]
                }, {
                    "name": "hearing_id_casehq",
                    "in": "query",
                    "type": "string",
                    "enum": ["5f2bffce29c77b6fef1e7422"]
                }, {
                    "name": "Source-System",
                    "in": "header",
                    "description": "soruce of the request initiation\n",
                    "required": true,
                    "type": "string",
                    "enum": ["SnL"]
                }, {
                    "name": "Destination-System",
                    "in": "header",
                    "description": "Target/Backend system that is supposed to consume the request message.",
                    "required": true,
                    "type": "string",
                    "enum": ["CFT"]
                }, {
                    "name": "Request-Created-At",
                    "in": "header",
                    "description": "Date and time of request initiation.",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Request-Type",
                    "in": "header",
                    "description": "Type of request",
                    "required": true,
                    "type": "string",
                    "enum": ["THEFT", "ASSAULT"]
                }, {
                    "name": "Request-Processed-At",
                    "in": "header",
                    "description": "Date & Time of Request Processing",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "Accept",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }, {
                    "name": "Content-Type",
                    "in": "header",
                    "required": true,
                    "type": "string",
                    "enum": ["application/json"]
                }],
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/rh-res-hearing-schedule"
                        },
                        "examples": {
                            "application/json": "[{\r\n  \"apiVersion\": \"V1.00103\",\r\n  \"transactionIdCaseHQ\": \"5f2bffce09fb0feadaf7b906\",\r\n  \"transactionIdHMCTS\": \"5f2bffcea47aedacc86d35cf\",\r\n  \"timeStamp\": \"12:15:22\",\r\n  \"listingId\": \"5f2bffcec0d5d73e929923fa\",\r\n  \"hearingIdCaseHQ\": \"5f2bffce29c77b6fef1e7488\",\r\n  \"hearingType\": \"Crime\",\r\n  \"hearingPriority\": \"High\",\r\n  \"hearingDate\": \"2020-01-28T07:57:08 -00:00\",\r\n  \"hearingStartTime\": \"08:45\",\r\n  \"hearingEndTime\": \"09:00\",\r\n  \"hearingWelshLanguage\": \"No\",\r\n  \"hearingPrivate\": \"Yes\",\r\n  \"hearingCaseIdHMCTS\": \"5f2bffcee0b6aa870e82f007\",\r\n  \"hearingSessionIdCaseHQ\": \"5f2bffceef36b0eaf339d884\",\r\n  \"hearingTranslatorRequired\": \"No\",\r\n  \"hearingTranslatorLanguage\": \"n/a\",\r\n  \"hearingOutcome\": \"To be hanged till death\",\r\n  \"hearingCreatedDate\": \"2019-12-28T07:57:08 -00:00\",\r\n  \"hearingCreatedBy\": \"Dimitry Mascaranhus\",\r\n  \"hearingParticipantId\": \"5f2bffce90a69eb81aaec725\",\r\n  \"hearingVenueId\": \"V3455\",\r\n  \"hearingRoomId\": \"R2345\",\r\n  \"hearingJudgeId\": \"HJ123\"\r\n}]"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rh-def": {
            "type": "object",
            "properties": {
                "Case Title": {
                    "type": "string"
                },
                "Case Id": {
                    "type": "string"
                },
                "TransactionIDHMCTS": {
                    "type": "string"
                },
                "Venue": {
                    "type": "string"
                },
                "Jurisdiction": {
                    "type": "string"
                },
                "Service": {
                    "type": "string"
                },
                "Case Type": {
                    "type": "string"
                },
                "Hearing Type": {
                    "type": "string"
                },
                "Priority": {
                    "type": "string"
                },
                "Status of the Listing Request": {
                    "type": "string"
                },
                "Ticket Type required ": {
                    "type": "string"
                },
                "Waiting time KPI": {
                    "type": "integer"
                },
                "Reason for STL change": {
                    "type": "string"
                },
                "Estimated Duration of the Hearing ": {
                    "type": "integer"
                },
                "Hearing channel": {
                    "type": "string"
                },
                "Private Hearing": {
                    "type": "boolean"
                },
                "Allocated Listing Team": {
                    "type": "string"
                }
            },
            "example": {
                "Case Title": "Divorce",
                "Case Id": "Div-24",
                "TransactionIDHMCTS": "TR123456",
                "Venue": "Manchester",
                "Jurisdiction": "String",
                "Service": "CFT",
                "Case Type": "Divore",
                "Hearing Type": "Civil",
                "Priority": "High",
                "Status of the Listing Request": "String",
                "Ticket Type required ": "String",
                "Waiting time KPI": 55,
                "Reason for STL change": "String",
                "Estimated Duration of the Hearing ": 30,
                "Hearing channel": "Online Streaming",
                "Private Hearing": true,
                "Allocated Listing Team": "Team A"
            }
        },
        "rh-res-hearing-schedule": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "apiVersion": {
                        "type": "string"
                    },
                    "transactionIdCaseHQ": {
                        "type": "string"
                    },
                    "transactionIdHMCTS": {
                        "type": "string"
                    },
                    "timeStamp": {
                        "type": "string"
                    },
                    "listingId": {
                        "type": "string"
                    },
                    "hearingIdCaseHQ": {
                        "type": "string"
                    },
                    "hearingType": {
                        "type": "string"
                    },
                    "hearingPriority": {
                        "type": "string"
                    },
                    "hearingDate": {
                        "type": "string"
                    },
                    "hearingStartTime": {
                        "type": "string"
                    },
                    "hearingEndTime": {
                        "type": "string"
                    },
                    "hearingWelshLanguage": {
                        "type": "string"
                    },
                    "hearingPrivate": {
                        "type": "string"
                    },
                    "hearingCaseIdHMCTS": {
                        "type": "string"
                    },
                    "hearingSessionIdCaseHQ": {
                        "type": "string"
                    },
                    "hearingTranslatorRequired": {
                        "type": "string"
                    },
                    "hearingTranslatorLanguage": {
                        "type": "string"
                    },
                    "hearingOutcome": {
                        "type": "string"
                    },
                    "hearingCreatedDate": {
                        "type": "string"
                    },
                    "hearingCreatedBy": {
                        "type": "string"
                    },
                    "hearingParticipantId": {
                        "type": "string"
                    },
                    "hearingVenueId": {
                        "type": "string"
                    },
                    "hearingRoomId": {
                        "type": "string"
                    },
                    "hearingJudgeId": {
                        "type": "string"
                    }
                },
                "required": ["apiVersion", "transactionIdCaseHQ", "transactionIdHMCTS", "timeStamp", "listingId", "hearingIdCaseHQ", "hearingType", "hearingPriority", "hearingDate", "hearingStartTime", "hearingEndTime", "hearingWelshLanguage", "hearingPrivate", "hearingCaseIdHMCTS", "hearingSessionIdCaseHQ", "hearingTranslatorRequired", "hearingTranslatorLanguage", "hearingOutcome", "hearingCreatedDate", "hearingCreatedBy", "hearingParticipantId", "hearingVenueId", "hearingRoomId", "hearingJudgeId"]
            }
        },
        "rh-upd-def": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "transactionIdHmcts": {
                    "type": "string"
                },
                "timeStamp": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "Destination": {
                    "type": "string"
                },
                "apiKey": {
                    "type": "string"
                },
                "apiAuthToken": {
                    "type": "string"
                },
                "corrolationID": {
                    "type": "string"
                },
                "caseObject": {
                    "type": "object",
                    "properties": {
                        "caseIdHmcts": {
                            "type": "integer"
                        },
                        "caseTitle": {
                            "type": "string"
                        },
                        "caseJurisdiction": {
                            "type": "string"
                        },
                        "caseService": {
                            "type": "string"
                        },
                        "CaseType": {
                            "type": "string"
                        },
                        "caseSubType": {
                            "type": "string"
                        },
                        "caseCourt": {
                            "type": "string"
                        },
                        "caseRegistered": {
                            "type": "string"
                        },
                        "caseComments": {
                            "type": "string"
                        },
                        "caseSource": {
                            "type": "string"
                        },
                        "caseKind": {
                            "type": "string"
                        },
                        "caseRelatedCaseIdHmcts": {
                            "type": "string"
                        },
                        "UpdateObject": {
                            "type": "string"
                        }
                    }
                },
                "listing": {
                    "type": "object",
                    "properties": {
                        "listingId": {
                            "type": "string"
                        },
                        "listingStartDate": {
                            "type": "string"
                        },
                        "listingEndDate": {
                            "type": "string"
                        },
                        "listingDuration": {
                            "type": "integer"
                        },
                        "listingType": {
                            "type": "string"
                        },
                        "listingPriority": {
                            "type": "string"
                        },
                        "listingNumberAttendees": {
                            "type": "integer"
                        },
                        "listingPartiesMethod": {
                            "type": "string"
                        }
                    }
                }
            },
            "example": {
                "apiVersion": "V1.00103",
                "transactionIdHmcts": "5f2bffce6962d03e8b73e76f",
                "timeStamp": "12:15:22",
                "source": "CR",
                "Destination": "SL",
                "apiKey": "c712b357-aaa2-4129-8394-68faa217e02d",
                "apiAuthToken": "kjlhsdg74iah2894648>IUH8hs@39Hi",
                "corrolationID": "5f2bffceb3f102a67269f969",
                "caseObject": {
                    "caseIdHmcts": 1.9830463505746397e+24,
                    "caseTitle": "Lori Clements \"vs\" Dawson Suarez",
                    "caseJurisdiction": "this.source",
                    "caseService": "MatterCat3",
                    "CaseType": "MatterCode1",
                    "caseSubType": "MatterType1",
                    "caseCourt": "Peterborough,Cambridgeshire,England",
                    "caseRegistered": "2014-06-23T02:49:41 -01:00",
                    "caseComments": "Amet irure ea consequat non exercitation est est qui commodo. Laborum officia ullamco exercitation laborum id dolor reprehenderit ullamco. Ut qui deserunt duis aliqua et reprehenderit magna laborum ullamco cillum.\r\nAnim ipsum exercitation cillum quis exercitation aliqua culpa dolor nostrud. Fugiat ut laboris dolore laborum excepteur. Do eu qui proident cillum.\r\nCillum est ullamco veniam nulla aliqua enim. Aliqua velit ipsum nulla anim reprehenderit. Sit est ex incididunt exercitation. Et et esse laborum incididunt non.\r\n",
                    "caseSource": "",
                    "caseKind": "Kind_1",
                    "caseRelatedCaseIdHmcts": "",
                    "UpdateObject": "Update is to close hearing as ressolved"
                },
                "listing": {
                    "listingId": "5f2bffcec0d5d73e929923fa",
                    "listingStartDate": "2015-01-02T05:29:13 -00:00",
                    "listingEndDate": "2014-09-08T03:13:14 -01:00",
                    "listingDuration": 30,
                    "listingType": "new",
                    "listingPriority": "High",
                    "listingNumberAttendees": 6,
                    "listingPartiesMethod": "In Person"
                }
            }
        },
        "rh-res-resources": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "VenueID": {
                        "type": "string"
                    },
                    "JurisdictionID": {
                        "type": "string"
                    },
                    "FacilityID": {
                        "type": "string"
                    },
                    "LocationID": {
                        "type": "string"
                    },
                    "RegionID": {
                        "type": "string"
                    },
                    "AddressID": {
                        "type": "string"
                    },
                    "UPRN": {
                        "type": "string"
                    },
                    "ePIMs": {
                        "type": "string"
                    },
                    "VenueName": {
                        "type": "string"
                    },
                    "VenueType": {
                        "type": "string"
                    },
                    "FacilityServiceLead": {
                        "type": "string"
                    },
                    "ReportingSIteName": {
                        "type": "string"
                    },
                    "CourtType": {
                        "type": "string"
                    },
                    "JoinedBuildingYN": {
                        "type": "string"
                    },
                    "OtherAgenciesAtSite": {
                        "type": "string"
                    },
                    "FlexibleOpsHours": {
                        "type": "string"
                    },
                    "Cluster": {
                        "type": "string"
                    },
                    "JudicialLead": {
                        "type": "string"
                    },
                    "DCJLCJLJArea": {
                        "type": "string"
                    },
                    "Status": {
                        "type": "string"
                    },
                    "OpeningTimes": {
                        "type": "string"
                    },
                    "OpenToPublic": {
                        "type": "string"
                    }
                },
                "required": ["VenueID", "JurisdictionID", "FacilityID", "LocationID", "RegionID", "AddressID", "UPRN", "ePIMs", "VenueName", "VenueType", "FacilityServiceLead", "ReportingSIteName", "CourtType", "JoinedBuildingYN", "OtherAgenciesAtSite", "FlexibleOpsHours", "Cluster", "JudicialLead", "DCJLCJLJArea", "Status", "OpeningTimes", "OpenToPublic"]
            }
        },
        "rh-res-resource": {
            "type": "object",
            "properties": {
                "VenueID": {
                    "type": "string"
                },
                "JurisdictionID": {
                    "type": "string"
                },
                "FacilityID": {
                    "type": "string"
                },
                "LocationID": {
                    "type": "string"
                },
                "RegionID": {
                    "type": "string"
                },
                "AddressID": {
                    "type": "string"
                },
                "UPRN": {
                    "type": "string"
                },
                "ePIMs": {
                    "type": "string"
                },
                "VenueName": {
                    "type": "string"
                },
                "VenueType": {
                    "type": "string"
                },
                "FacilityServiceLead": {
                    "type": "string"
                },
                "ReportingSIteName": {
                    "type": "string"
                },
                "CourtType": {
                    "type": "string"
                },
                "JoinedBuildingYN": {
                    "type": "string"
                },
                "OtherAgenciesAtSite": {
                    "type": "string"
                },
                "FlexibleOpsHours": {
                    "type": "string"
                },
                "Cluster": {
                    "type": "string"
                },
                "JudicialLead": {
                    "type": "string"
                },
                "DCJLCJLJArea": {
                    "type": "string"
                },
                "Status": {
                    "type": "string"
                },
                "OpeningTimes": {
                    "type": "string"
                },
                "OpenToPublic": {
                    "type": "string"
                }
            }
        },
        "rh-del-def": {
            "type": "object",
            "properties": {
                "deleteMethod": {
                    "type": "string"
                },
                "deleteMessage": {
                    "type": "string"
                },
                "listingRequestId": {
                    "type": "string"
                },
                "hearingIdCaseHQ": {
                    "type": "string"
                }
            },
            "example": {
                "deleteMethod": "C",
                "deleteMessage": "Cancel the request as no longer needed settled out of court",
                "listingRequestId": "lrq123",
                "hearingIdCaseHQ": "hidchq123"
            }
        }
    },
    "tags": []
}
